// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/brickzzhang/zero-helloworld/user/rpc/internal/logic"
	"github.com/brickzzhang/zero-helloworld/user/rpc/internal/svc"
	"github.com/brickzzhang/zero-helloworld/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserPassword(ctx context.Context, in *user.GetUserPasswordRequest) (*user.GetUserPasswordResponse, error) {
	l := logic.NewGetUserPasswordLogic(ctx, s.svcCtx)
	return l.GetUserPassword(in)
}
